
FROM python:3.11-slim-bookworm

#### SETUP PACKAGE ####
WORKDIR /rsi_mfi_notify
RUN pip install --upgrade pip
RUN PATH=/usr/local/bin
COPY requirements_prod.txt requirements.txt
RUN pip install -r requirements.txt
COPY setup.py setup.py
COPY app app
RUN pip install .

#### SETUP VARIABLES ####
ENV SES_HOST_ADDRESS=""
ENV SES_USERNAME=""
ENV SES_USER_ID=""
ENV SES_PASSWORD=""
ENV SES_FROM=""
ENV SES_TO=""

ENTRYPOINT python3 app/main.py

